server:
  servlet:
    context-path: /api
    session:
      timeout: 1m

api:
  key: 68fadb44593d4273a3783baa310424dd

baseUrl: https://api.rawg.io/api

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password